//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.01 at 01:19:09 CEST 
//


package be.ac.ulg.montefiore.run.totem.util.jaxb.totemBase;


/**
 * Java content class for anonymous complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/data/software/totem/totem.git/src/resources/TOTEM-base/TOTEM-base-v1_0.xsd line 24)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="type" use="required" type="{}unitsType" />
 *       &lt;attribute name="value" use="required" type="{}unitsValue" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface UnitType {


    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link be.ac.ulg.montefiore.run.totem.util.jaxb.totemBase.BandwidthUnits}
     *     {@link be.ac.ulg.montefiore.run.totem.util.jaxb.totemBase.DelayUnits}
     */
    java.lang.Object getValue();

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link be.ac.ulg.montefiore.run.totem.util.jaxb.totemBase.BandwidthUnits}
     *     {@link be.ac.ulg.montefiore.run.totem.util.jaxb.totemBase.DelayUnits}
     */
    void setValue(java.lang.Object value);

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link be.ac.ulg.montefiore.run.totem.util.jaxb.totemBase.UnitsType}
     */
    be.ac.ulg.montefiore.run.totem.util.jaxb.totemBase.UnitsType getType();

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link be.ac.ulg.montefiore.run.totem.util.jaxb.totemBase.UnitsType}
     */
    void setType(be.ac.ulg.montefiore.run.totem.util.jaxb.totemBase.UnitsType value);

}
