//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v@@BUILD_VERSION@@ 
// 	See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// 	Any modifications to this file will be lost upon recompilation of the source schema. 
// 	Generated on: 2007.03.26 � 05:48:59 CEST 
//


package be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.impl;

public class JAXBVersion {

    public final static java.lang.String version = "1.0.4";

}
