//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v@@BUILD_VERSION@@ 
// 	See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// 	Any modifications to this file will be lost upon recompilation of the source schema. 
// 	Generated on: 2007.03.26 � 05:48:59 CEST 
//


package be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb;


/**
 * Java content class for anonymous complex type.
 * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/home/lepropre/projects/run-totem/src/resources/scenario/CPLEX-MCNF-Scenario-v1_0.xsd line 27)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://jaxb.model.scenario.totem.run.montefiore.ulg.ac.be}ASTMEventType">
 *       &lt;sequence>
 *         &lt;element name="objectiveFunction">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://jaxb.model.scenario.totem.run.montefiore.ulg.ac.be}param" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="formulation">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;sequence>
 *                     &lt;element name="nodeLink">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                   &lt;sequence>
 *                     &lt;element name="linkPath">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;attribute name="nbPaths" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="displayTEMetrics" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="exportModelToFile" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="verbose" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface ComputeMCNFOptimalRoutingType
    extends be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.ASTMEventType
{


    /**
     * Gets the value of the verbose property.
     * 
     */
    boolean isVerbose();

    /**
     * Sets the value of the verbose property.
     * 
     */
    void setVerbose(boolean value);

    boolean isSetVerbose();

    void unsetVerbose();

    /**
     * Gets the value of the exportModelToFile property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getExportModelToFile();

    /**
     * Sets the value of the exportModelToFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setExportModelToFile(java.lang.String value);

    boolean isSetExportModelToFile();

    void unsetExportModelToFile();

    /**
     * Gets the value of the displayTEMetrics property.
     * 
     */
    boolean isDisplayTEMetrics();

    /**
     * Sets the value of the displayTEMetrics property.
     * 
     */
    void setDisplayTEMetrics(boolean value);

    boolean isSetDisplayTEMetrics();

    void unsetDisplayTEMetrics();

    /**
     * Gets the value of the formulation property.
     * 
     * @return
     *     possible object is
     *     {@link be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ComputeMCNFOptimalRoutingType.FormulationType}
     */
    be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ComputeMCNFOptimalRoutingType.FormulationType getFormulation();

    /**
     * Sets the value of the formulation property.
     * 
     * @param value
     *     allowed object is
     *     {@link be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ComputeMCNFOptimalRoutingType.FormulationType}
     */
    void setFormulation(be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ComputeMCNFOptimalRoutingType.FormulationType value);

    boolean isSetFormulation();

    void unsetFormulation();

    /**
     * Gets the value of the objectiveFunction property.
     * 
     * @return
     *     possible object is
     *     {@link be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ComputeMCNFOptimalRoutingType.ObjectiveFunctionType}
     */
    be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ComputeMCNFOptimalRoutingType.ObjectiveFunctionType getObjectiveFunction();

    /**
     * Sets the value of the objectiveFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ComputeMCNFOptimalRoutingType.ObjectiveFunctionType}
     */
    void setObjectiveFunction(be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ComputeMCNFOptimalRoutingType.ObjectiveFunctionType value);

    boolean isSetObjectiveFunction();

    void unsetObjectiveFunction();


    /**
     * Java content class for anonymous complex type.
     * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/home/lepropre/projects/run-totem/src/resources/scenario/CPLEX-MCNF-Scenario-v1_0.xsd line 40)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;sequence>
     *           &lt;element name="nodeLink">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *         &lt;/sequence>
     *         &lt;sequence>
     *           &lt;element name="linkPath">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;attribute name="nbPaths" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *         &lt;/sequence>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface FormulationType {


        /**
         * Gets the value of the nodeLink property.
         * 
         * @return
         *     possible object is
         *     {@link be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ComputeMCNFOptimalRoutingType.FormulationType.NodeLinkType}
         */
        be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ComputeMCNFOptimalRoutingType.FormulationType.NodeLinkType getNodeLink();

        /**
         * Sets the value of the nodeLink property.
         * 
         * @param value
         *     allowed object is
         *     {@link be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ComputeMCNFOptimalRoutingType.FormulationType.NodeLinkType}
         */
        void setNodeLink(be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ComputeMCNFOptimalRoutingType.FormulationType.NodeLinkType value);

        boolean isSetNodeLink();

        void unsetNodeLink();

        /**
         * Gets the value of the linkPath property.
         * 
         * @return
         *     possible object is
         *     {@link be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ComputeMCNFOptimalRoutingType.FormulationType.LinkPathType}
         */
        be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ComputeMCNFOptimalRoutingType.FormulationType.LinkPathType getLinkPath();

        /**
         * Sets the value of the linkPath property.
         * 
         * @param value
         *     allowed object is
         *     {@link be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ComputeMCNFOptimalRoutingType.FormulationType.LinkPathType}
         */
        void setLinkPath(be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ComputeMCNFOptimalRoutingType.FormulationType.LinkPathType value);

        boolean isSetLinkPath();

        void unsetLinkPath();


        /**
         * Java content class for anonymous complex type.
         * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/home/lepropre/projects/run-totem/src/resources/scenario/CPLEX-MCNF-Scenario-v1_0.xsd line 49)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="nbPaths" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface LinkPathType {


            /**
             * Gets the value of the nbPaths property.
             * 
             */
            int getNbPaths();

            /**
             * Sets the value of the nbPaths property.
             * 
             */
            void setNbPaths(int value);

            boolean isSetNbPaths();

            void unsetNbPaths();

        }


        /**
         * Java content class for anonymous complex type.
         * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/home/lepropre/projects/run-totem/src/resources/scenario/CPLEX-MCNF-Scenario-v1_0.xsd line 44)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface NodeLinkType {


        }

    }


    /**
     * Java content class for anonymous complex type.
     * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/home/lepropre/projects/run-totem/src/resources/scenario/CPLEX-MCNF-Scenario-v1_0.xsd line 32)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://jaxb.model.scenario.totem.run.montefiore.ulg.ac.be}param" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface ObjectiveFunctionType {


        /**
         * Gets the value of the Param property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the Param property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParam().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.Param}
         * {@link be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.ParamType}
         * 
         */
        java.util.List getParam();

        boolean isSetParam();

        void unsetParam();

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getName();

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setName(java.lang.String value);

        boolean isSetName();

        void unsetName();

    }

}
