//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v@@BUILD_VERSION@@ 
// 	See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// 	Any modifications to this file will be lost upon recompilation of the source schema. 
// 	Generated on: 2007.03.26 � 05:48:59 CEST 
//


package be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
public class ObjectFactory
    extends be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.DefaultJAXBContextImpl
{

    private static java.util.HashMap defaultImplementations = new java.util.HashMap(16, 0.75F);
    private static java.util.HashMap rootTagMap = new java.util.HashMap();
    public final static be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.GrammarInfo grammarInfo = new be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.GrammarInfoImpl(rootTagMap, defaultImplementations, (be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ObjectFactory.class));
    public final static java.lang.Class version = (be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.impl.JAXBVersion.class);

    static {
        defaultImplementations.put((be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ComputeMCNFOptimalRouting.class), "be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.ComputeMCNFOptimalRouting");
        defaultImplementations.put((be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ComputeMCNFOptimalRoutingType.FormulationType.class), "be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.impl.ComputeMCNFOptimalRoutingTypeImpl.FormulationTypeImpl");
        defaultImplementations.put((be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ComputeMCNFOptimalRoutingType.FormulationType.LinkPathType.class), "be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.impl.ComputeMCNFOptimalRoutingTypeImpl.FormulationTypeImpl.LinkPathTypeImpl");
        defaultImplementations.put((be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ComputeMCNFOptimalRoutingType.class), "be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.impl.ComputeMCNFOptimalRoutingTypeImpl");
        defaultImplementations.put((be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ComputeMCNFOptimalRoutingType.ObjectiveFunctionType.class), "be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.impl.ComputeMCNFOptimalRoutingTypeImpl.ObjectiveFunctionTypeImpl");
        defaultImplementations.put((be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ComputeMCNFOptimalRoutingType.FormulationType.NodeLinkType.class), "be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.impl.ComputeMCNFOptimalRoutingTypeImpl.FormulationTypeImpl.NodeLinkTypeImpl");
        rootTagMap.put(new javax.xml.namespace.QName("http://jaxb.model.scenario.cplexMCNF.repository.totem.run.montefiore.ulg.ac.be", "ComputeMCNFOptimalRouting"), (be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ComputeMCNFOptimalRouting.class));
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb
     * 
     */
    public ObjectFactory() {
        super(grammarInfo);
    }

    /**
     * Create an instance of the specified Java content interface.
     * 
     * @param javaContentInterface
     *     the Class object of the javacontent interface to instantiate
     * @return
     *     a new instance
     * @throws JAXBException
     *     if an error occurs
     */
    public java.lang.Object newInstance(java.lang.Class javaContentInterface)
        throws javax.xml.bind.JAXBException
    {
        return super.newInstance(javaContentInterface);
    }

    /**
     * Get the specified property. This method can only be
     * used to get provider specific properties.
     * Attempting to get an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name
     *     the name of the property to retrieve
     * @return
     *     the value of the requested property
     * @throws PropertyException
     *     when there is an error retrieving the given property or value
     */
    public java.lang.Object getProperty(java.lang.String name)
        throws javax.xml.bind.PropertyException
    {
        return super.getProperty(name);
    }

    /**
     * Set the specified property. This method can only be
     * used to set provider specific properties.
     * Attempting to set an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param value
     *     the value of the property to be set
     * @param name
     *     the name of the property to retrieve
     * @throws PropertyException
     *     when there is an error processing the given property or value
     */
    public void setProperty(java.lang.String name, java.lang.Object value)
        throws javax.xml.bind.PropertyException
    {
        super.setProperty(name, value);
    }

    /**
     * Create an instance of ComputeMCNFOptimalRouting
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ComputeMCNFOptimalRouting createComputeMCNFOptimalRouting()
        throws javax.xml.bind.JAXBException
    {
        return new be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.ComputeMCNFOptimalRouting();
    }

    /**
     * Create an instance of ComputeMCNFOptimalRoutingTypeFormulationType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ComputeMCNFOptimalRoutingType.FormulationType createComputeMCNFOptimalRoutingTypeFormulationType()
        throws javax.xml.bind.JAXBException
    {
        return new be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.impl.ComputeMCNFOptimalRoutingTypeImpl.FormulationTypeImpl();
    }

    /**
     * Create an instance of ComputeMCNFOptimalRoutingTypeFormulationTypeLinkPathType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ComputeMCNFOptimalRoutingType.FormulationType.LinkPathType createComputeMCNFOptimalRoutingTypeFormulationTypeLinkPathType()
        throws javax.xml.bind.JAXBException
    {
        return new be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.impl.ComputeMCNFOptimalRoutingTypeImpl.FormulationTypeImpl.LinkPathTypeImpl();
    }

    /**
     * Create an instance of ComputeMCNFOptimalRoutingType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ComputeMCNFOptimalRoutingType createComputeMCNFOptimalRoutingType()
        throws javax.xml.bind.JAXBException
    {
        return new be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.impl.ComputeMCNFOptimalRoutingTypeImpl();
    }

    /**
     * Create an instance of ComputeMCNFOptimalRoutingTypeObjectiveFunctionType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ComputeMCNFOptimalRoutingType.ObjectiveFunctionType createComputeMCNFOptimalRoutingTypeObjectiveFunctionType()
        throws javax.xml.bind.JAXBException
    {
        return new be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.impl.ComputeMCNFOptimalRoutingTypeImpl.ObjectiveFunctionTypeImpl();
    }

    /**
     * Create an instance of ComputeMCNFOptimalRoutingTypeFormulationTypeNodeLinkType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.ComputeMCNFOptimalRoutingType.FormulationType.NodeLinkType createComputeMCNFOptimalRoutingTypeFormulationTypeNodeLinkType()
        throws javax.xml.bind.JAXBException
    {
        return new be.ac.ulg.montefiore.run.totem.repository.cplexMCNF.scenario.model.jaxb.impl.ComputeMCNFOptimalRoutingTypeImpl.FormulationTypeImpl.NodeLinkTypeImpl();
    }

}
