//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.01 at 09:07:08 CEST 
//


package nl.tudelft.repository.externalRouting.routing.model.jaxb;


/**
 * Java content class for anonymous complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/data/software/totem/totem.git/src/resources/routing/ExternalRouting-Routing-v0_1.xsd line 18)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="routing" type="{http://jaxb.model.routing.externalRouting.repository.tudelft.nl}routing" minOccurs="0"/>
 *         &lt;element name="lsps" type="{http://jaxb.model.routing.externalRouting.repository.tudelft.nl}lsps" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface ExternalRoutingType {


    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getName();

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setName(java.lang.String value);

    boolean isSetName();

    void unsetName();

    /**
     * Gets the value of the lsps property.
     * 
     * @return
     *     possible object is
     *     {@link nl.tudelft.repository.externalRouting.routing.model.jaxb.Lsps}
     */
    nl.tudelft.repository.externalRouting.routing.model.jaxb.Lsps getLsps();

    /**
     * Sets the value of the lsps property.
     * 
     * @param value
     *     allowed object is
     *     {@link nl.tudelft.repository.externalRouting.routing.model.jaxb.Lsps}
     */
    void setLsps(nl.tudelft.repository.externalRouting.routing.model.jaxb.Lsps value);

    boolean isSetLsps();

    void unsetLsps();

    /**
     * Gets the value of the routing property.
     * 
     * @return
     *     possible object is
     *     {@link nl.tudelft.repository.externalRouting.routing.model.jaxb.Routing}
     */
    nl.tudelft.repository.externalRouting.routing.model.jaxb.Routing getRouting();

    /**
     * Sets the value of the routing property.
     * 
     * @param value
     *     allowed object is
     *     {@link nl.tudelft.repository.externalRouting.routing.model.jaxb.Routing}
     */
    void setRouting(nl.tudelft.repository.externalRouting.routing.model.jaxb.Routing value);

    boolean isSetRouting();

    void unsetRouting();

}
