//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.01 at 09:07:08 CEST 
//


package nl.tudelft.repository.externalRouting.routing.model.jaxb;


/**
 * Java content class for flowValue complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/data/software/totem/totem.git/src/resources/routing/ExternalRouting-Routing-v0_1.xsd line 34)
 * <p>
 * <pre>
 * &lt;complexType name="flowValue">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="flow">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="src" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="dst" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="link">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="src" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="dst" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="util" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface FlowValue {


    /**
     * Gets the value of the flow property.
     * 
     * @return
     *     possible object is
     *     {@link nl.tudelft.repository.externalRouting.routing.model.jaxb.FlowValue.FlowType}
     */
    nl.tudelft.repository.externalRouting.routing.model.jaxb.FlowValue.FlowType getFlow();

    /**
     * Sets the value of the flow property.
     * 
     * @param value
     *     allowed object is
     *     {@link nl.tudelft.repository.externalRouting.routing.model.jaxb.FlowValue.FlowType}
     */
    void setFlow(nl.tudelft.repository.externalRouting.routing.model.jaxb.FlowValue.FlowType value);

    boolean isSetFlow();

    void unsetFlow();

    /**
     * Gets the value of the util property.
     * 
     */
    float getUtil();

    /**
     * Sets the value of the util property.
     * 
     */
    void setUtil(float value);

    boolean isSetUtil();

    void unsetUtil();

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link nl.tudelft.repository.externalRouting.routing.model.jaxb.FlowValue.LinkType}
     */
    nl.tudelft.repository.externalRouting.routing.model.jaxb.FlowValue.LinkType getLink();

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link nl.tudelft.repository.externalRouting.routing.model.jaxb.FlowValue.LinkType}
     */
    void setLink(nl.tudelft.repository.externalRouting.routing.model.jaxb.FlowValue.LinkType value);

    boolean isSetLink();

    void unsetLink();


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/data/software/totem/totem.git/src/resources/routing/ExternalRouting-Routing-v0_1.xsd line 37)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="src" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="dst" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface FlowType {


        /**
         * Gets the value of the dst property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getDst();

        /**
         * Sets the value of the dst property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setDst(java.lang.String value);

        boolean isSetDst();

        void unsetDst();

        /**
         * Gets the value of the src property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getSrc();

        /**
         * Sets the value of the src property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setSrc(java.lang.String value);

        boolean isSetSrc();

        void unsetSrc();

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/data/software/totem/totem.git/src/resources/routing/ExternalRouting-Routing-v0_1.xsd line 45)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="src" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="dst" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface LinkType {


        /**
         * Gets the value of the dst property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getDst();

        /**
         * Sets the value of the dst property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setDst(java.lang.String value);

        boolean isSetDst();

        void unsetDst();

        /**
         * Gets the value of the src property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getSrc();

        /**
         * Sets the value of the src property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setSrc(java.lang.String value);

        boolean isSetSrc();

        void unsetSrc();

    }

}
