//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.01 at 05:02:38 CEST 
//


package nl.tudelft.repository.externalRouting.routing.model.jaxb;


/**
 * Java content class for lsps complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/data/software/totem/totem.git/src/resources/routing/ExternalRouting-Routing-v0_1.xsd line 45)
 * <p>
 * <pre>
 * &lt;complexType name="lsps">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lsp" type="{http://jaxb.model.routing.externalRouting.repository.tudelft.nl}lsp" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface Lsps {


    /**
     * Gets the value of the Lsp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the Lsp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLsp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link nl.tudelft.repository.externalRouting.routing.model.jaxb.Lsp}
     * 
     */
    java.util.List getLsp();

    boolean isSetLsp();

    void unsetLsp();

}
