//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.01 at 05:02:38 CEST 
//


package nl.tudelft.repository.externalRouting.routing.model.jaxb;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.tudelft.repository.externalRouting.routing.model.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
public class ObjectFactory
    extends be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.DefaultJAXBContextImpl
{

    private static java.util.HashMap defaultImplementations = new java.util.HashMap(16, 0.75F);
    private static java.util.HashMap rootTagMap = new java.util.HashMap();
    public final static be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.GrammarInfo grammarInfo = new be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.GrammarInfoImpl(rootTagMap, defaultImplementations, (nl.tudelft.repository.externalRouting.routing.model.jaxb.ObjectFactory.class));
    public final static java.lang.Class version = (nl.tudelft.repository.externalRouting.routing.model.jaxb.impl.JAXBVersion.class);

    static {
        defaultImplementations.put((nl.tudelft.repository.externalRouting.routing.model.jaxb.Route.class), "nl.tudelft.repository.externalRouting.routing.model.Route");
        defaultImplementations.put((nl.tudelft.repository.externalRouting.routing.model.jaxb.UnitType.class), "nl.tudelft.repository.externalRouting.routing.model.jaxb.impl.UnitTypeImpl");
        defaultImplementations.put((nl.tudelft.repository.externalRouting.routing.model.jaxb.ExternalRouting.class), "nl.tudelft.repository.externalRouting.routing.model.ExternalRouting");
        defaultImplementations.put((nl.tudelft.repository.externalRouting.routing.model.jaxb.Unit.class), "nl.tudelft.repository.externalRouting.routing.model.jaxb.impl.UnitImpl");
        defaultImplementations.put((nl.tudelft.repository.externalRouting.routing.model.jaxb.Lsps.class), "nl.tudelft.repository.externalRouting.routing.model.Lsps");
        defaultImplementations.put((nl.tudelft.repository.externalRouting.routing.model.jaxb.Lsp.PathType.class), "nl.tudelft.repository.externalRouting.routing.model.jaxb.impl.LspImpl.PathTypeImpl");
        defaultImplementations.put((nl.tudelft.repository.externalRouting.routing.model.jaxb.ExternalRoutingType.class), "nl.tudelft.repository.externalRouting.routing.model.jaxb.impl.ExternalRoutingTypeImpl");
        defaultImplementations.put((nl.tudelft.repository.externalRouting.routing.model.jaxb.Lsp.class), "nl.tudelft.repository.externalRouting.routing.model.Lsp");
        defaultImplementations.put((nl.tudelft.repository.externalRouting.routing.model.jaxb.Routing.class), "nl.tudelft.repository.externalRouting.routing.model.Routing");
        rootTagMap.put(new javax.xml.namespace.QName("http://jaxb.model.routing.externalRouting.repository.tudelft.nl", "unit"), (nl.tudelft.repository.externalRouting.routing.model.jaxb.Unit.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://jaxb.model.routing.externalRouting.repository.tudelft.nl", "ExternalRouting"), (nl.tudelft.repository.externalRouting.routing.model.jaxb.ExternalRouting.class));
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.tudelft.repository.externalRouting.routing.model.jaxb
     * 
     */
    public ObjectFactory() {
        super(grammarInfo);
    }

    /**
     * Create an instance of the specified Java content interface.
     * 
     * @param javaContentInterface
     *     the Class object of the javacontent interface to instantiate
     * @return
     *     a new instance
     * @throws JAXBException
     *     if an error occurs
     */
    public java.lang.Object newInstance(java.lang.Class javaContentInterface)
        throws javax.xml.bind.JAXBException
    {
        return super.newInstance(javaContentInterface);
    }

    /**
     * Get the specified property. This method can only be
     * used to get provider specific properties.
     * Attempting to get an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name
     *     the name of the property to retrieve
     * @return
     *     the value of the requested property
     * @throws PropertyException
     *     when there is an error retrieving the given property or value
     */
    public java.lang.Object getProperty(java.lang.String name)
        throws javax.xml.bind.PropertyException
    {
        return super.getProperty(name);
    }

    /**
     * Set the specified property. This method can only be
     * used to set provider specific properties.
     * Attempting to set an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name
     *     the name of the property to retrieve
     * @param value
     *     the value of the property to be set
     * @throws PropertyException
     *     when there is an error processing the given property or value
     */
    public void setProperty(java.lang.String name, java.lang.Object value)
        throws javax.xml.bind.PropertyException
    {
        super.setProperty(name, value);
    }

    /**
     * Create an instance of Route
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public nl.tudelft.repository.externalRouting.routing.model.jaxb.Route createRoute()
        throws javax.xml.bind.JAXBException
    {
        return new nl.tudelft.repository.externalRouting.routing.model.Route();
    }

    /**
     * Create an instance of UnitType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public nl.tudelft.repository.externalRouting.routing.model.jaxb.UnitType createUnitType()
        throws javax.xml.bind.JAXBException
    {
        return new nl.tudelft.repository.externalRouting.routing.model.jaxb.impl.UnitTypeImpl();
    }

    /**
     * Create an instance of ExternalRouting
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public nl.tudelft.repository.externalRouting.routing.model.jaxb.ExternalRouting createExternalRouting()
        throws javax.xml.bind.JAXBException
    {
        return new nl.tudelft.repository.externalRouting.routing.model.ExternalRouting();
    }

    /**
     * Create an instance of Unit
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public nl.tudelft.repository.externalRouting.routing.model.jaxb.Unit createUnit()
        throws javax.xml.bind.JAXBException
    {
        return new nl.tudelft.repository.externalRouting.routing.model.jaxb.impl.UnitImpl();
    }

    /**
     * Create an instance of Lsps
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public nl.tudelft.repository.externalRouting.routing.model.jaxb.Lsps createLsps()
        throws javax.xml.bind.JAXBException
    {
        return new nl.tudelft.repository.externalRouting.routing.model.Lsps();
    }

    /**
     * Create an instance of LspPathType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public nl.tudelft.repository.externalRouting.routing.model.jaxb.Lsp.PathType createLspPathType()
        throws javax.xml.bind.JAXBException
    {
        return new nl.tudelft.repository.externalRouting.routing.model.jaxb.impl.LspImpl.PathTypeImpl();
    }

    /**
     * Create an instance of ExternalRoutingType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public nl.tudelft.repository.externalRouting.routing.model.jaxb.ExternalRoutingType createExternalRoutingType()
        throws javax.xml.bind.JAXBException
    {
        return new nl.tudelft.repository.externalRouting.routing.model.jaxb.impl.ExternalRoutingTypeImpl();
    }

    /**
     * Create an instance of Lsp
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public nl.tudelft.repository.externalRouting.routing.model.jaxb.Lsp createLsp()
        throws javax.xml.bind.JAXBException
    {
        return new nl.tudelft.repository.externalRouting.routing.model.Lsp();
    }

    /**
     * Create an instance of Routing
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public nl.tudelft.repository.externalRouting.routing.model.jaxb.Routing createRouting()
        throws javax.xml.bind.JAXBException
    {
        return new nl.tudelft.repository.externalRouting.routing.model.Routing();
    }

}
