//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.01 at 05:02:38 CEST 
//


package nl.tudelft.repository.externalRouting.routing.model.jaxb;


/**
 * Java content class for route complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/data/software/totem/totem.git/src/resources/routing/ExternalRouting-Routing-v0_1.xsd line 34)
 * <p>
 * <pre>
 * &lt;complexType name="route">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="src" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dst" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;choice>
 *           &lt;element name="load" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *           &lt;element name="util" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface Route {


    /**
     * Gets the value of the util property.
     * 
     */
    float getUtil();

    /**
     * Sets the value of the util property.
     * 
     */
    void setUtil(float value);

    boolean isSetUtil();

    void unsetUtil();

    /**
     * Gets the value of the load property.
     * 
     */
    float getLoad();

    /**
     * Sets the value of the load property.
     * 
     */
    void setLoad(float value);

    boolean isSetLoad();

    void unsetLoad();

    /**
     * Gets the value of the dst property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getDst();

    /**
     * Sets the value of the dst property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setDst(java.lang.String value);

    boolean isSetDst();

    void unsetDst();

    /**
     * Gets the value of the src property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getSrc();

    /**
     * Sets the value of the src property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setSrc(java.lang.String value);

    boolean isSetSrc();

    void unsetSrc();

}
