//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.01 at 05:02:38 CEST 
//


package nl.tudelft.repository.externalRouting.routing.model.jaxb;


/**
 * Java content class for anonymous complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at http://totem.run.montefiore.ulg.ac.be/Schema/TOTEM-base-v1_0.xsd line 24)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="type" use="required" type="{http://jaxb.model.routing.externalRouting.repository.tudelft.nl}unitsType" />
 *       &lt;attribute name="value" use="required" type="{http://jaxb.model.routing.externalRouting.repository.tudelft.nl}unitsValue" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface UnitType {


    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link nl.tudelft.repository.externalRouting.routing.model.jaxb.DelayUnits}
     *     {@link nl.tudelft.repository.externalRouting.routing.model.jaxb.BandwidthUnits}
     */
    java.lang.Object getValue();

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link nl.tudelft.repository.externalRouting.routing.model.jaxb.DelayUnits}
     *     {@link nl.tudelft.repository.externalRouting.routing.model.jaxb.BandwidthUnits}
     */
    void setValue(java.lang.Object value);

    boolean isSetValue();

    void unsetValue();

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link nl.tudelft.repository.externalRouting.routing.model.jaxb.UnitsType}
     */
    nl.tudelft.repository.externalRouting.routing.model.jaxb.UnitsType getType();

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link nl.tudelft.repository.externalRouting.routing.model.jaxb.UnitsType}
     */
    void setType(nl.tudelft.repository.externalRouting.routing.model.jaxb.UnitsType value);

    boolean isSetType();

    void unsetType();

}
