//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.01 at 04:43:16 CEST 
//


package nl.tudelft.repository.externalRouting.scenario.model.jaxb;


/**
 * Java content class for loadExternalRouting element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/data/software/totem/totem.git/src/resources/scenario/ExternalRouting-Scenario-v0_1.xsd line 30)
 * <p>
 * <pre>
 * &lt;element name="loadExternalRouting">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;extension base="{http://jaxb.model.scenario.totem.run.montefiore.ulg.ac.be}ASTMEventType">
 *         &lt;attribute name="llcId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="routingFile" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/extension>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 */
public interface LoadExternalRouting
    extends javax.xml.bind.Element, nl.tudelft.repository.externalRouting.scenario.model.jaxb.LoadExternalRoutingType
{


}
